# Numpy Task 2



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [6]:
print(np.__version__)

1.20.3


In [7]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nikita/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nikita/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nikita/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nikita/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nikita/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nikita/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nikita/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nikita/anaconda3\\Library\\include']


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [13]:
a = [1,2,3,4,5,6,7,8,9]
np.size(a)

9

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [14]:
np.info(a)

Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [13]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [14]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [17]:
b = np.arange(5,10)
print(b)
print(b[::-1])

[5 6 7 8 9]
[9 8 7 6 5]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [16]:
a = np.arange(0,9)
b = a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [18]:
c = np.nonzero([1,2,0,0,4,0])
c

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [19]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [22]:
a = np.random.random([3,3,3])
a

array([[[0.39069386, 0.87891635, 0.37301714],
        [0.41698196, 0.15457777, 0.00578677],
        [0.46934798, 0.30535362, 0.05778781]],

       [[0.55981644, 0.92226108, 0.44682475],
        [0.82783545, 0.12577782, 0.0193211 ],
        [0.4971795 , 0.7089302 , 0.99326322]],

       [[0.95556292, 0.2426833 , 0.48734388],
        [0.52619789, 0.87826425, 0.31681622],
        [0.09127354, 0.75065174, 0.74644513]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [25]:
a = np.random.random([10,10])
print(a)
print()
b = a.min()
print('min value in the array is:')
print(b)
print()
c = a.max()
print('max value in the array is:')
print(c)

[[0.97906167 0.56809339 0.76415804 0.38932929 0.41049414 0.4228663
  0.30698715 0.08288862 0.30038438 0.17279147]
 [0.28497482 0.81671354 0.89604533 0.26992801 0.18091066 0.11257197
  0.40728929 0.64979717 0.79474261 0.75840837]
 [0.85852393 0.25568348 0.79790965 0.04978053 0.42553637 0.07219625
  0.13290475 0.75922999 0.84221958 0.91555563]
 [0.35395517 0.3884562  0.55007645 0.57079123 0.79912848 0.25318481
  0.5037645  0.72754621 0.43274499 0.70736294]
 [0.13530676 0.3777894  0.48385304 0.18103565 0.04675452 0.24886252
  0.25310842 0.27569951 0.36516622 0.81876241]
 [0.81966297 0.92741797 0.10562087 0.03662176 0.32945107 0.71031312
  0.75400992 0.62747946 0.64235172 0.21985458]
 [0.53180106 0.8633348  0.52002288 0.61411025 0.03753892 0.14129195
  0.87558919 0.7902844  0.52777188 0.01091511]
 [0.18014551 0.19281603 0.83868572 0.69844381 0.50862596 0.95431779
  0.63801423 0.21545252 0.57143099 0.35780235]
 [0.30740434 0.88871416 0.53922866 0.80077366 0.96620803 0.37690942
  0.51832797 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [27]:
a= np.random.random(30)
print(a)
print()
print('The maean of the values is: ', a.mean())

[0.05061199 0.58329718 0.00769253 0.09096811 0.08629891 0.82043797
 0.69818344 0.1800786  0.02549556 0.63312661 0.74169048 0.06262959
 0.97051495 0.28357232 0.94648327 0.72451111 0.34624914 0.96617056
 0.80864627 0.83769634 0.60257903 0.37822107 0.22515833 0.07919446
 0.62117195 0.98396789 0.74021195 0.69962443 0.55285659 0.69673645]

The maean of the values is:  0.5148025699393126


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [35]:
a = np.ones((6,6))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [37]:
a = np.ones((6,6))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [31]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [43]:
a = np.diag(1+np.arange(4), k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [54]:
a = np.zeros((8,8), dtype=int)
print ('the original array is:')
print(a)
print()
print()
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print('The checkerboard array will be:')
print(a)

the original array is:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


The checkerboard array will be:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [60]:
a = np.unravel_index(100,(6,7,8))
a

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [63]:
x=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [15]:
a = np.random.randn(5,5)
print(a.min())
print(a.max())

-1.801627868270095
2.4061872778377493


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [69]:
a = np.dtype([("R", np.ubyte), ("G", np.ubyte), ("B", np.ubyte), ("A", np.ubyte)])
a

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [73]:
x = np.dot(np.array((5,3)), np.array((3,2)))
print(x)

21


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [82]:
#negate: make the signs opposite.
a = np.arange(15)
a[(a>3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [95]:
#solution: sum of array ranging for 5 is 10, and sum of array(-1) is null.
#hence, the output is 10.

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

#np.array(0) / np.array(0)

#np.array(0) // np.array(0)

$np.array([np.nan]).astype(int).astype(float)

In [ ]:
# array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [100]:
a = np.random.uniform((2,2))
a

array([1.46528489, 1.06994475])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [102]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7,8])
np.intersect1d(a,b)

array([4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [105]:
a = np.array([1,2,3,4,'t'])
print(np.seterr())

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#Solution: False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [121]:
#lets say, today date is 5.
np.datetime64('5')
yesterday = np.datetime64('5') - np.timedelta64(1)
today     = np.datetime64('5')
tomorrow  = np.datetime64('5') + np.timedelta64(1)
print(today)
print(yesterday)
print(tomorrow)

0005
0004
0006


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [125]:
a= np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [128]:
a= np.zeros((5,5))
a+= np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [145]:
a = np.random.rand(10)
a.sort()
a

array([0.04844236, 0.08614974, 0.13683628, 0.1757609 , 0.25054572,
       0.34234706, 0.58047051, 0.63273132, 0.73869533, 0.8946051 ])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [136]:
a = np.random.rand(10)
a.sort()
a

array([0.07704278, 0.27050653, 0.3004639 , 0.31902804, 0.47340872,
       0.6177906 , 0.63346099, 0.70727882, 0.72878124, 0.79536058])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [150]:
a = np.arange(50)
print(np.add.reduce(a))

1225


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [151]:
a = np.random.rand(5)
b = np.random.rand(5)
print(np.array_equal(a,b))

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [162]:
a = np.random.rand(10,2)
print(np.sqrt(a))

[[0.3110078  0.1230437 ]
 [0.98390036 0.2780605 ]
 [0.70956804 0.55055929]
 [0.71529535 0.23787283]
 [0.69815547 0.77755481]
 [0.8788959  0.78874747]
 [0.18548131 0.9399567 ]
 [0.9094822  0.71284497]
 [0.57185916 0.64793007]
 [0.82383832 0.88937606]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [177]:
a = np.random.rand(10)
print('Original random value array is: ', a)

print('')

a.sort()
print('The sorted values are: ', a)

print('')

a[a.argmax()] = 0
print('Array obtained by replacing max value by zero:', a)

Original random value array is:  [0.75527263 0.61906824 0.50314191 0.3521991  0.37736038 0.57103421
 0.75014604 0.35979697 0.2976911  0.58601372]

The sorted values are:  [0.2976911  0.3521991  0.35979697 0.37736038 0.50314191 0.57103421
 0.58601372 0.61906824 0.75014604 0.75527263]

Array obtained by replacing max value by zero: [0.2976911  0.3521991  0.35979697 0.37736038 0.50314191 0.57103421
 0.58601372 0.61906824 0.75014604 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [180]:
a = np.arange(10, dtype=int)
print(np.info())

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000018F9DA63B80>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [189]:
a = np.arange(10)
print(np.set_printoptions(a))

None


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [200]:
a = np.random.rand(5)
print(a.argmin())

4


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [205]:
a = np.random.rand(7)
a.argsort()

array([3, 6, 5, 2, 0, 4, 1], dtype=int64)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [206]:
a = np.random.rand(7)
a.any()

True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [219]:
a = np.random.rand(5)
b = np.random.rand(5)
np.diag(np.dot(a,b))

ValueError: Input must be 1- or 2-d.

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)